language: cpp
before_install:
  - sudo apt-get install cmake
script: 
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./test/test.run
  - ./load_test
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
notifications:
  recipients:
    - wuyanyi09@foxmail.com
  email:
    on_success: change
    on_failure: always
